---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: "true"
  labels:
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: syndesis-server
  name: fuse-ignite-server
spec:
  tags:
  - from:
      kind: DockerImage
      name: $SERVER$
    importPolicy:
      scheduled: true
      insecure: true
    name: "$TAG$"
---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: "true"
  labels:
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: syndesis-ui
  name: fuse-ignite-ui
spec:
  tags:
  - from:
      kind: DockerImage
      name: $UI$
    importPolicy:
      scheduled: true
      insecure: true
    name: "$TAG$"
---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: "true"
  labels:
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: syndesis-meta
  name: fuse-ignite-meta
spec:
  tags:
  - from:
      kind: DockerImage
      name: $META$
    importPolicy:
      scheduled: true
      insecure: true
    name: "$TAG$"
---
apiVersion: v1
kind: ImageStream
metadata:
  name: oauth-proxy
  labels:
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: syndesis-oauthproxy
spec:
  tags:
  - from:
      kind: DockerImage
      name: $OAUTH_PROXY$
    importPolicy:
      scheduled: true
    name: "$OAUTH_PROXY_TAG$"
---
apiVersion: v1
kind: ImageStream
metadata:
  name: prometheus
  labels:
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: syndesis-prometheus
spec:
  tags:
  - from:
      kind: DockerImage
      name: $PROMETHEUS$
    importPolicy:
      scheduled: true
    name: "$PROMETHEUS_TAG$"
---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: "true"
  labels:
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: s2i-java
  name: fuse-ignite-s2i
spec:
  tags:
  - from:
      kind: DockerImage
      name: $S2I$
    importPolicy:
      scheduled: true
      insecure: true
    name: "$TAG$"
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: postgres_exporter
  annotations:
    openshift.io/image.insecureRepository: "true"
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: syndesis-db-metrics
spec:
  tags:
  - from:
      kind: DockerImage
      name: $POSTGRES_EXPORTER$
    importPolicy:
      scheduled: true
    name: "$POSTGRES_EXPORTER_TAG$"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syndesis-operator
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
imagePullSecrets:
  - name: "syndesis-pull-secret"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: syndesis-operator
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
rules:
- apiGroups:
  - syndesis.io
  resources:
  - "*"
  - "*/finalizers"
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - configmaps
  - secrets
  - serviceaccounts
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs: [ get ]
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  - replicationcontrollers/scale
  - replicationcontrollers/status
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
- apiGroups:
  - ""
  - build.openshift.io
  resources:
  - builds
  - buildconfigs
  - builds/details
  - buildconfigs/webhooks
  - buildconfigs/instantiatebinary
  - builds/log
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
- apiGroups:
  - ""
  - apps.openshift.io
  resources:
  - deploymentconfigs
  - deploymentconfigs/scale
  verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
- apiGroups:
  - ""
  - apps.openshift.io
  resources:
  - deploymentconfigrollbacks
  - deploymentconfigs/instantiate
  - deploymentconfigs/rollback
  verbs: [ create ]
- apiGroups:
  - ""
  - apps.openshift.io
  resources:
  - deploymentconfigs/log
  - deploymentconfigs/status
  verbs: [ get, list, watch ]
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreamimages
  - imagestreammappings
  - imagestreams/secrets
  - imagestreamtags
  verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreams/status
  - imagestreamimports
  verbs: [ get, list, watch ]
- apiGroups:
  - ""
  resources:
  - events
  verbs: [ get, list ]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
- apiGroups:
  - ""
  - template.openshift.io
  resources:
  - processedtemplates
  - templateconfigs
  - templateinstances
  - templates
  verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
- apiGroups:
  - authorization.openshift.io
  resources:
  - rolebindings
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
- apiGroups:
  - camel.apache.org
  resources:
  - "*"
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  - prometheusrules
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
- apiGroups:
  - integreatly.org
  resources:
  - grafanadashboards
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs: [ get, list, watch ]
- apiGroups:
  - eventing.knative.dev
  resources:
  - channels
  verbs: [ get, list, watch ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: syndesis-operator:install
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
subjects:
- kind: ServiceAccount
  name: syndesis-operator
roleRef:
  kind: Role
  name: syndesis-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: syndesis-operator:view
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
subjects:
- kind: ServiceAccount
  name: syndesis-operator
roleRef:
  name: view
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: syndesis-operator:edit
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
subjects:
- kind: ServiceAccount
  name: syndesis-operator
roleRef:
  name: edit
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: "true"
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
  name: fuse-online-operator
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      # Keep tag 'latest' here, its used as an anchor in the release script
      name: $OPERATOR$
    importPolicy:
      scheduled: true
    name: "$TAG$"
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: syndesis-operator
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
      syndesis.io/app: syndesis
      syndesis.io/type: operator
      syndesis.io/component: syndesis-operator
  template:
    metadata:
      labels:
        syndesis.io/app: syndesis
        syndesis.io/type: operator
        syndesis.io/component: syndesis-operator
    spec:
      serviceAccountName: syndesis-operator
      containers:
        - name: syndesis-operator
          image: ' '
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 60000
            name: metrics
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "syndesis-operator"
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - syndesis-operator
      from:
        kind: ImageStreamTag
        name: fuse-online-operator:$TAG$
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: "true"
  labels:
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: komodo-server
  name: fuse-komodo-server
spec:
  tags:
  - from:
      kind: DockerImage
      name: $KOMODO_SERVER$
    importPolicy:
      scheduled: true
      insecure: true
    name: "$KOMODO_SERVER_TAG$"
