#!/bin/bash

if [[ "$2" == *"syndesisio/syndesis-qe"* ]]; then
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	echo "! Direct push to upstream is not allowed !"
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	exit 1
fi
